#plugin
source-file ~/.config/tmux/tmux.reset.conf
source-file ~/.config/tmux/buffer.conf
# run-shell ~/.config/tmux/focus.tmux
set-option -g default-terminal screen-256color
set-option -g terminal-overrides ',xterm-256color:RGB'


set -g prefix ^A
set -g base-index 1              # start indexing windows at 1 instead of 0
set -g detach-on-destroy off     # don't exit from tmux when closing a session
set -g escape-time 0             # zero-out escape time delay
set -g history-limit 1000000     # increase history size (from 2,000)
set -g renumber-windows on       # renumber all windows when any window is closed
set -g set-clipboard on          # use system clipboard
set -g status-position top       # macOS / darwin style
setw -g mode-keys vi
set -g pane-active-border-style 'fg=cyan,bg=default'
set -g pane-border-style 'fg=brightblack,bg=default'
set -g pane-border-lines double

# Indicate active pane by colouring only half of the border in windows with 
# exactly two panes, by displaying arrow markers, by drawing both or neither.
# [off | colour | arrows | both]
set -g pane-border-indicators both

set -g @fzf-url-fzf-options '-p 60%,30% --prompt="   " --border-label=" Open URL "'
set -g @fzf-url-history-limit '2000'

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-continuum'
#
# set-option -g default-command "reattach-to-user-namespace -l $SHELL"
set -g @yank_selection_mouse 'clipboard'


set -g @continuum-restore 'on'
set -g @resurrect-strategy-nvim 'session'

# theme catppuccino
# Some basic mocha colors.
set -g @ctp_active_bg "#24273A"
set -g @ctp_inactive_bg "#3E4154"
set -g @ctp_surface_1 "#494d64"
set -g @ctp_fg "#cad3f5"
set -g @ctp_mauve "#c6a0f6"
set -g @ctp_crust "#181926"
set -g focus-events on


# Create vertical split
unbind '|'
bind '|' split-window -h

# Create horizontal split
unbind '-'
bind - split-window -v

run '~/.tmux/plugins/tpm/tpm'
