# status bar theme
set -g status-bg default
set -g status-justify 'left'
set -g status-left-length '100'
set -g status 'on'
set -g status-right-length '100'
setw -g window-status-separator ''
set -g status-style bg=default   

# Set colors transparently #00000033
set -g @ctp_black "#00000033"
# Colors
set -g @ctp_default default
set -g @ctp_lavender "#b7bdf8"
set -g @ctp_blue "#8aadf4"
set -g @ctp_sapphire "#7dc4e4"
set -g @ctp_sky "#91d7e3"
set -g @ctp_teal "#8bd5ca"
set -g @ctp_green "#a6da95"
set -g @ctp_yellow "#eed49f"
set -g @ctp_peach "#f5a97f"
set -g @ctp_maroon "#ee99a0"
set -g @ctp_red "#ed8796"
set -g @ctp_mauve "#c6a0f6"
set -g @ctp_pink "#f5bde6"
set -g @ctp_flamingo "#f0c6c6"
set -g @ctp_rosewater "#f4dbd6"

set -g status-left '#{?client_prefix,#[fg=#{@ctp_peach}] #[fg=black bg=#{@ctp_peach}] #[bg=#{@ctp_blue}] #S#[fg=#{@ctp_blue} bg=#{@ctp_default}]#[bg=#{@ctp_default} fg=#{@ctp_default}] ,#[fg=#{@ctp_yellow} bg=#{@ctp_default}] #[bg=#{@ctp_yellow}, fg=black, bold] #[bg=#{@ctp_blue}, fg=black, nobold] #S#[bg=#{@ctp_default}, fg=#{@ctp_blue}] }'

setw -g window-status-format ' #[fg=#8A8EA0] #[bg=#0000, bold] #(~/.config/tmux/tmux_prefix.sh #W) #[bg=#{@ctp_sapphire},fg=black] #I #[bg=#24273A, fg=#{@ctp_sapphire}]' 
setw -g window-status-current-format '   #[fg=#{@ctp_peach}, bold]#(~/.config/tmux/tmux_prefix.sh #W) #[bg=#{@ctp_peach},fg=black] #I #[bg=#{@ctp_default}, fg=#{@ctp_peach}]' 
#
set -g status-right '#[fg=#{@ctp_pink}]#[bg=#{@ctp_pink},fg=black]󱂵 #[bg=#{@ctp_rosewater}] #(~/.config/tmux/tmux_path.sh #{pane_current_path})#[bg=#{@ctp_default}, fg=#{@ctp_rosewater}] #(~/.config/tmux/tmux_gitbranch.sh #{pane_current_path})#[bg=#{@ctp_default}, fg=#{@ctp_default}]    '
